# Generated by Django 3.2.16 on 2023-01-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follwing',
            new_name='following',
        ),
    ]
